name: Deploy to GitHub Pages

on:
  push:
    branches:
      - release
      - '!main'
      - '!develop'
      - '!*/*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - run: npm ci

      - run: npm run build
        env:
          TURBO_TOKEN: ${{ secrets.SUNSET_WIND_TURBO_TOKEN }}
          TURBO_TEAM: a2softhouse

      - name: Deploy storybook
        working-directory: ./app/docs
        run: npm run deploy-storybook -- --ci --existing-output-dir=storybook-static --source-branch=release
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
