name: Publish to NPM

on:
  push:
    branch:
      - release
    branches-ignore:
      - main
      - develop
# concurrency: ${{ github.workflow }}-${{ github.ref }}

# jobs:
#   release:
#     name: Publish NPM
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repo
#         uses: actions/checkout@v3

#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 16
#           cache: 'npm'
#           cache-dependency-path: '**/package-lock.json'

#       - run: npm ci

#       - name: Publish to NPM
#         id: changesets
#         uses: changesets/action@v1
#         with:
#           publish: npm run publish-release
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           NPM_TOKEN: ${{ secrets.SUNSET_UI_NPM_TOKEN }}
#           TURBO_TOKEN: ${{ secrets.SUNSET_UI_TURBO_TOKEN }}
#           TURBO_TEAM: a2softhouse
