name: Release and Publish NPM
on:
  pull_request:
    branches:
      - release
      - '!main'
      - '!develop'
      - '!*/*'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release and Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - run: npm ci

      - name: Publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run release:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.SUNSET_WIND_NPM_TOKEN }}
          TURBO_TOKEN: ${{ secrets.SUNSET_WIND_TURBO_TOKEN }}
          TURBO_TEAM: a2softhouse
